Add ROCm blurbs to linux installation instructions
pytorch/pytorch.github.io pull request #1096
Opened 2022-08-08 22:36 UTC by jithunnair-amd

@jeffdaily @pensun please review

2022-08-10 18:46 UTC, jeffdaily commented on _get_started/installation/linux.md
> +To install PyTorch via Anaconda, and do not have a [CUDA-capable](https://developer.nvidia.com/cuda-zone) or [ROCm-capable](https://docs.amd.com) system or do not require CUDA/ROCm (ie. GPU support),
```suggestion
To install PyTorch via Anaconda, and do not have a [CUDA-capable](https://developer.nvidia.com/cuda-zone) or [ROCm-capable](https://docs.amd.com) system or do not require CUDA/ROCm (i.e. GPU support), in the above selector, choose OS: Linux, Package: Conda, Language: Python and Compute Platform: CPU.
```

2022-08-10 18:47 UTC, jeffdaily commented on _get_started/installation/linux.md
> +To install PyTorch via pip, and do not have a [CUDA-capable](https://developer.nvidia.com/cuda-zone) or [ROCm-capable](https://docs.amd.com) system or do not require CUDA/ROCm (ie. GPU support), in t
```suggestion
To install PyTorch via pip, and do not have a [CUDA-capable](https://developer.nvidia.com/cuda-zone) or [ROCm-capable](https://docs.amd.com) system or do not require CUDA/ROCm (i.e. GPU support), in the above selector, choose OS: Linux, Package: Pip, Language: Python and Compute Platform: CPU.
```

2022-08-10 18:48 UTC, jeffdaily requested changes
Two nit changes requested.  Otherwise LGTM.

2022-08-22 15:29 UTC, jithunnair-amd commented
cc @atalman @malfet Who should be added as reviewer for this PR?

2022-08-22 15:35 UTC, merged