build: build the Pytorch 1.13 release blog post
pytorch/pytorch.github.io pull request #1166
Opened 2022-10-26 18:24 UTC by hydroxyhelium

2022-10-27 16:34 UTC, svekars commented on _posts/2022-10-25-Pytorch-1.13-Release.md
> +Learn more with our [tutorial](https://github.com/pytorch/tutorials/pull/2072).
should go to https://pytorch.org/tutorials/recipes/profile_with_itt.html

2022-10-28 15:15 UTC, malfet approved these changes

2022-10-28 15:15 UTC, malfet commented on _posts/2022-10-25-Pytorch-1.13-Release.md
> +### (Prototype) ARM® Compute Library (ACL) backend support for AWS Graviton
```suggestion
### (Prototype) Arm® Compute Library (ACL) backend support for AWS Graviton
```

2022-10-28 15:15 UTC, malfet commented on _posts/2022-10-25-Pytorch-1.13-Release.md
> +We achieved substantial improvements for CV and NLP inference on aarch64 cpu with Advanced RISC Machine (ARM) Compute Library (acl) to enable acl backend for pytorch and torch-xla modules.Highlights
```suggestion
We achieved substantial improvements for CV and NLP inference on aarch64 cpu with Arm Compute Library (acl) to enable acl backend for pytorch and torch-xla modules. Highlights include:
```

2022-10-28 16:16 UTC, malfet commented
@hydroxyhelium why did you force pushed? Please apply updates I've made

2022-10-28 16:17 UTC, malfet requested changes
Why are we changing source files?

2022-10-28 17:32 UTC, closed without merging