upgrade ruby version, lockfile and edge blog
pytorch/pytorch.github.io pull request #1816
Opened 2024-11-16 02:24 UTC by msaroufim

2024-11-18 16:15 UTC, svekars commented
I disagree that we should delete the edge.html page without giving it more thought . If it is decided to be deprecated, it needs to be replaced with a redirect to other relevant page. Also, the whole Edge dropdown with just 1 item won't make a lot of sense.

2024-11-26 19:15 UTC, msaroufim commented
I chatted with @ali-khosh offline and he said he'd fine with this change if I can guarantee that the redirects are working

2024-11-26 19:33 UTC, malfet approved these changes

2024-11-26 19:33 UTC, malfet commented on edge.html
> +redirect_to: /executorch-overview
It's weird that this thing is called .html, while it's clearly not :)

2024-11-26 20:27 UTC, cjyabraham requested changes
Looks ok, however, you'll also need to update _includes/mobile_menu.html so that it matches your changes to main_menu.html.

2024-11-26 21:28 UTC, jennbly commented
I'd suggest that we not have an option in the middle of the drop down menu without a drop down. Could we instead move to under "Ecosystem" or "Learn"?

2024-11-26 21:36 UTC, cjyabraham commented
> > Looks ok, however, you'll also need to update _includes/mobile_menu.html so that it matches your changes to main_menu.html.
> 
> can you take a look again please?

The mobile menu still doesn't match with the desktop menu.

BTW, why not put the "Edge" menu item under the "Learn" menu or some other menu rather than have it standing by itself?

2024-11-26 21:38 UTC, msaroufim commented on _includes/mobile_menu.html
> -          <li>
@cjyabraham was this not what you were asking about?

2024-11-26 21:57 UTC, cjyabraham approved these changes

2024-11-26 21:59 UTC, merged

2024-11-26 22:54 UTC, ali-khosh commented
> BTW, why not put the "Edge" menu item under the "Learn" menu or some other menu rather than have it standing by itself?
Edge is a key strategic bet and we'd like to keep it more visible.

2024-11-27 21:39 UTC, cjyabraham commented
I'm having trouble running the site locally on MacOS after this upgrade. I've upgraded ruby, however, I'm now getting this: https://gist.github.com/cjyabraham/5f12926a985e77acb986bc70f4bd7125

Any advice?