Update stable and nightly links to ROCm4.5.2
pytorch/pytorch.github.io pull request #977
Opened 2022-03-18 22:32 UTC by jithunnair-amd

2022-03-23 18:41 UTC, malfet requested changes
@jithunnair-amd please make changes to https://github.com/pytorch/pytorch.github.io/blob/site/published_versions.json and regenerate `assets/quick-start-module.js` by running:
```
python3 scripts/gen_quick_start_module.py >assets/quick-start-module.js
```

2022-03-30 04:01 UTC, jithunnair-amd commented
@malfet This looks good now. Please check.

2022-04-04 18:04 UTC, jithunnair-amd commented
gentle ping @malfet @seemethere

2022-04-04 20:39 UTC, seemethere approved these changes

2022-04-04 21:12 UTC, merged